###
DELETE http://127.0.0.1/joomla5x/api/index.php/v1/joomgallery/categories/10
Accept: application/vnd.api+json
Content-Type: application/json
X-Joomla-Token: c2hhMjU2Ojc3OTo3MDIxODdiNTE0N2NjMDY0ZjVlNGY3OTk5NmNiOWZhZTcxYWRkNWVmOWJjZDA0YjYxZTVjNWEwMmEwZTVkZmY5